Algoritmo TP2_Ej5_ConErrores_1
	// EL PROGRAMA DEBE EMITIR
	// UN SOLO RESULTADO
	// EL DIAGRAMA MUESTRA 3 RESULTADOS
	// DE LOS CUALES 1 VA A TENER VALOR
	// Y LOS OTROS 2 TIENEN VALOR BASURA
	Leer IMPSD
	Si IMPSD>500 Entonces
		IMPCD_A = IMPSD*0.85
	SiNo
		Si IMPSD>100 Entonces
			IMPCD_B = IMPSD*0.90
		SiNo
			IMPCD_C = IMPSD*0.95
		FinSi
	FinSi
	Escribir IMPCD_A,IMPCD_B,IMPCD_C
FinAlgoritmo
