Algoritmo GUIA01EJ15_v02
	Leer MINUTOS
	RDIAS = MINUTOS%1440
	DIAS = (MINUTOS-RDIAS)/1440
	RHORAS = RDIAS%60
	HORAS = (RDIAS-RHORAS)/60
	Escribir 'DIAS: ',DIAS
	Escribir 'HORAS: ',HORAS
	Escribir 'MINUTOS: ',RHORAS
FinAlgoritmo
