#include <iostream>

using namespace std;

int main(){
    string nombre, apellido;     /// DECLARACION DE VARIABLES DE TIPO STRING PARA ALMACENAR TEXTO (CADENAS DE CARACTERES).
    int edad;

    /// SE INGRESA EL NUMERO ENTERO. 'CIN' LEE LOS CARACTERES NUMERICOS,
    /// PERO DEJA EL CARACTER DE SALTO DE LINEA ('\N' O ENTER) ATRAPADO
    /// EN EL BUFER DE ENTRADA.

    cin >> edad;

    /// CRUCIAL: SE LIMPIA EL BUFER. 'CIN.IGNORE()' DESCARTA EL ENTER
    /// QUE QUEDO FLOTANDO.
    /// SI NO PUSIERAMOS ESTO, EL SIGUIENTE 'GETLINE' LEERIA ESE ENTER
    /// VACIO Y SALTARIA
    /// DIRECTAMENTE A LA SIGUIENTE INSTRUCCION SIN DEJAR QUE EL USUARIO
    /// ESCRIBA NADA.

    cin.ignore(); /// LIMPIA EL BUFFER QUE QUEDA LUEGO DE PRESIONAR UN ENTER AL INGRESAR UN NUMERO


    /// 'GETLINE' LEE TODA LA LINEA INTRODUCIDA POR EL USUARIO HASTA QUE
    /// PRESIONA ENTER.
    /// A DIFERENCIA DE 'CIN >> NOMBRE', 'GETLINE' SI ACEPTA LOS ESPACIOS
    /// EN BLANCO (POR EJEMPLO, SI EL USUARIO SE LLAMA "JUAN CARLOS").

    getline(cin, nombre);       /// PERMITE INGRESAR TEXTOS DONDE EL ESPACIO (BARRA ESPACIADORA) ES TOMADO COMO UN CARACTER NORMAL, NO UN ENTER.

    /// LEE EL APELLIDO DE LA MISMA MANERA, PERMITIENDO APELLIDOS COMPUESTOS (EJ: "ALFARO MORENO").

    getline(cin, apellido);

    cout << "Edad: " << edad << endl;
    cout << "Nombre: " << nombre << endl;
    cout << "Apellido: " << apellido << endl;

    return 0;
}
