Algoritmo GUIA04EJ18
	// PTO B: MAXIMO CARRERA DISTANCIA
	BAND_MAX_DIST = 0
	// PTO D: MINIMO CARRERA GENERAL
	BAND_MIN_CARR = 0
	Escribir 'INGRESE CODIGO DE CARRERA: '
	Leer CARR
	Escribir 'INGRESE LEGAJO DEL ALUMNO: '
	Leer LEG
	Mientras (LEG!=0) Hacer
		CARR_ACTUAL = CARR
		// REINICIAR POR CARRERA
		// PTO A Y D
		CONT_INS_CARR = 0
		// PTO B
		CONT_DIST = 0
		// PTO C
		CONT_M = 0
		CONT_T = 0
		CONT_N = 0
		Mientras (LEG!=0) && (CARR==CARR_ACTUAL) Hacer
			Escribir 'CODIGO DE MATERIA: '
			Leer MAT
			Escribir 'MODALIDAD (P: PRESENCIAL / D: DISTANCIA): '
			Leer MOD
			Escribir 'HORARIO (M: MAÑANA / T: TARDE / N: NOCHE): '
			Leer HOR
			// PTO A: CONTAR INSCRIPCIONES TOTALES DE LA CARRERA
			CONT_INS_CARR = CONT_INS_CARR+1
			// PTO B: CONTAR MODALIDAD DISTANCIA
			Si (MOD=='D') Entonces
				CONT_DIST = CONT_DIST+1
			FinSi
			// PTO C: CONTAR POR HORARIO
			Si (HOR=='M') Entonces
				CONT_M = CONT_M+1
			FinSi
			Si (HOR=='T') Entonces
				CONT_T = CONT_T+1
			FinSi
			Si (HOR=='N') Entonces
				CONT_N = CONT_N+1
			FinSi
			Escribir 'INGRESE CODIGO DE CARRERA: '
			Leer CARR
			Escribir 'INGRESE LEGAJO DEL ALUMNO: '
			Leer LEG
		FinMientras
		// INFORMES POR CARRERA
		// PTO A
		Escribir 'A) CANTIDAD DE INSCRIPCIONES CARRERA ',CARR_ACTUAL,': ',CONT_INS_CARR
		// PTO C: PORCENTAJES POR CARRERA
		PORC_M = (CONT_M*100)/CONT_INS_CARR
		PORC_T = (CONT_T*100)/CONT_INS_CARR
		PORC_N = (CONT_N*100)/CONT_INS_CARR
		Escribir 'C) PORCENTAJES DE HORARIOS EN CARRERA ',CARR_ACTUAL,':'
		Escribir 'MAÑANA: ',PORC_M,'%'
		Escribir 'TARDE: ',PORC_T,'%'
		Escribir 'NOCHE: ',PORC_N,'%'
		// PTO B: EVALUAR MAXIMO DISTANCIA
		Si (BAND_MAX_DIST == 0) || (CONT_DIST > MAX_DIST_GRAL) Entonces
			MAX_DIST_GRAL = CONT_DIST
			CARR_MAX_DIST = CARR_ACTUAL
			BAND_MAX_DIST = 1
		FinSi
		// PTO D: EVALUAR MINIMO INSCRIPCIONES GENERAL
		Si (BAND_MIN_CARR ==0 ) || (CONT_INS_CARR < MIN_INS_GRAL) Entonces
			MIN_INS_GRAL = CONT_INS_CARR
			CARR_MIN_GRAL = CARR_ACTUAL
			BAND_MIN_CARR = 1
		FinSi
	FinMientras
	// PTO B
	Escribir 'B) CARRERA CON MAS INSCRIPCIONES A DISTANCIA: ',CARR_MAX_DIST
	// PTO D
	Escribir 'D) CARRERA CON MENOS INSCRIPCIONES REGISTRADAS: ',CARR_MIN_GRAL
FinAlgoritmo
